# Generated by Django 4.0 on 2022-01-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='alias',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
